<?php
if (! defined('ABSPATH')) { exit; }
$sectionArgs = isset($args) && is_array($args) ? $args : [];
$locale = (string) ($sectionArgs['locale'] ?? rosa_preview_locale());
$c = static fn(string $key, string $en, string $ar): string => rosa_preview_section_value($sectionArgs, 'contact', $key, $locale, $locale === 'ar' ? $ar : $en);
$address = rosa_preview_business_value('address', $locale);
$phone = rosa_theme_business_value('phone');
$email = rosa_theme_business_value('email');
?>
<section class="rosa-preview-contact" data-preview-contact-layout id="inquiry"><div class="rosa-preview-rail rosa-preview-contact__grid"><div class="rosa-preview-contact__details"><?php if($address!==''): ?><article data-preview-contact-location><span><?php echo esc_html($c('location_label','Location','الموقع')); ?></span><strong><?php echo esc_html($address); ?></strong></article><?php endif; ?><?php if($phone!==''): ?><article data-preview-contact-phone><span><?php echo esc_html($c('phone_label','Call us','اتصل بنا')); ?></span><a href="tel:<?php echo esc_attr((string)preg_replace('/[^0-9+]/','',$phone)); ?>"><bdi dir="ltr"><?php echo esc_html($phone); ?></bdi></a></article><?php endif; ?><?php if($email!==''): ?><article data-preview-contact-email><span><?php echo esc_html($c('email_label','Email us','البريد الإلكتروني')); ?></span><a href="mailto:<?php echo esc_attr($email); ?>"><bdi dir="ltr"><?php echo esc_html($email); ?></bdi></a></article><?php endif; ?></div><div class="rosa-preview-contact__form-wrap"><h2><?php echo esc_html($c('form_title','Share your requirements','شارك متطلباتك')); ?></h2><form class="rosa-preview-contact-form" data-preview-contact-form><label><?php echo esc_html($c('field_name','Name','الاسم')); ?><input type="text" name="name" autocomplete="name"></label><label><?php echo esc_html($c('field_phone','Phone','الهاتف')); ?><input type="tel" name="phone" autocomplete="tel" dir="ltr"></label><label><?php echo esc_html($c('field_subject','Subject','الموضوع')); ?><input type="text" name="subject"></label><label><?php echo esc_html($c('field_message','Message','الرسالة')); ?><textarea name="message" rows="5"></textarea></label><?php if($email!==''): ?><a class="rosa-preview-button rosa-preview-button--accent" href="mailto:<?php echo esc_attr($email); ?>"><?php echo esc_html($c('send_email','Send by email','إرسال عبر البريد الإلكتروني')); ?></a><?php endif; ?></form></div></div></section>
