<?php
/** Template Name: Rosa Client Preview Home */
if (! defined('ABSPATH')) { exit; }
$locale = rosa_preview_locale();
get_header();
?>
<div data-preview-hero><?php get_template_part('template-parts/client-preview/hero', null, ['locale'=>$locale]); ?></div>
<section class="rosa-preview-split" data-preview-who-we-are><div class="rosa-preview-rail rosa-preview-split__grid"><div class="rosa-preview-split__media"><?php $img=rosa_preview_media_id('about_procurement'); if($img>0) echo wp_get_attachment_image($img,'large'); ?></div><div><p class="rosa-preview-eyebrow"><?php echo esc_html(rosa_preview_copy('who_eyebrow',$locale)); ?></p><h2><?php echo esc_html(rosa_preview_copy('who_title',$locale)); ?></h2><p><?php echo esc_html($locale==='ar'?'نساعد المشترين على استكشاف فئات الأدوات ومراجع الكتالوج والتواصل للحصول على دعم التوريد.':'We help buyers explore instrument families and catalogue references, then contact Rosa for procurement support.'); ?></p><a class="rosa-preview-text-link" href="<?php echo esc_url(home_url($locale==='ar'?'/ar/about/':'/about/')); ?>"><?php echo esc_html($locale==='ar'?'اعرف المزيد':'Learn more'); ?></a></div></div></section>
<section class="rosa-preview-stats" data-preview-stats><div class="rosa-preview-rail rosa-preview-stats__grid"><?php $stats=$locale==='ar'?[['5','فئات منتجات'],['5','كتالوجات'],['2','لغات للمعاينة']]:[['5','Product families'],['5','Catalogue PDFs'],['2','Preview languages']]; foreach($stats as [$n,$label]): ?><div><strong><?php echo esc_html($n); ?></strong><span><?php echo esc_html($label); ?></span></div><?php endforeach; ?></div></section>
<div data-preview-featured-products><?php get_template_part('template-parts/client-preview/product-grid',null,['title'=>$locale==='ar'?'منتجات مختارة':'Editor’s Choice','limit'=>4,'context'=>'featured','locale'=>$locale]); ?></div>
<div data-preview-value-strip><?php get_template_part('template-parts/client-preview/value-strip',null,['locale'=>$locale]); ?></div>
<section class="rosa-preview-feature" data-preview-feature-banner><div class="rosa-preview-rail rosa-preview-feature__grid"><div><?php $img=rosa_preview_media_id('procurement_support'); if($img>0) echo wp_get_attachment_image($img,'large'); ?></div><div><p class="rosa-preview-eyebrow"><?php echo esc_html($locale==='ar'?'دعم التوريد':'Procurement support'); ?></p><h2><?php echo esc_html($locale==='ar'?'من الكتالوج إلى طلب عرض السعر':'From catalogue reference to quotation request'); ?></h2><p><?php echo esc_html($locale==='ar'?'استكشف الأدوات حسب الفئة وتواصل معنا بالمراجع المطلوبة.':'Browse instruments by family and contact us with the references you need.'); ?></p></div></div></section>
<div data-preview-latest-products><?php get_template_part('template-parts/client-preview/product-grid',null,['title'=>$locale==='ar'?'أحدث المنتجات':'Latest Products','limit'=>4,'context'=>'latest','locale'=>$locale]); ?></div>
<section class="rosa-preview-promos" data-preview-promos><div class="rosa-preview-rail rosa-preview-promos__grid"><a href="<?php echo esc_url(home_url($locale==='ar'?'/ar/shop/':'/shop/')); ?>"><strong><?php echo esc_html($locale==='ar'?'تصفح المقصات الجراحية':'Browse surgical scissors'); ?></strong><span><?php echo esc_html($locale==='ar'?'استكشف مراجع الفئة':'Explore family references'); ?></span></a><a href="<?php echo esc_url(home_url($locale==='ar'?'/ar/shop/':'/shop/')); ?>"><strong><?php echo esc_html($locale==='ar'?'استكشف كتالوجات الأدوات':'Explore instrument catalogues'); ?></strong><span><?php echo esc_html($locale==='ar'?'خمس فئات رئيسية':'Five primary families'); ?></span></a></div></section>
<section class="rosa-preview-why" data-preview-why-us><div class="rosa-preview-rail"><p class="rosa-preview-eyebrow">ROSA</p><h2><?php echo esc_html(rosa_preview_copy('why_title',$locale)); ?></h2><div class="rosa-preview-why__grid"><article><h3><?php echo esc_html($locale==='ar'?'مراجع واضحة':'Clear references'); ?></h3><p><?php echo esc_html($locale==='ar'?'اعمل باستخدام أسماء الفئات ومراجع المنتجات.':'Work with family names and product references.'); ?></p></article><article><h3><?php echo esc_html($locale==='ar'?'تكوينات دقيقة':'Exact configurations'); ?></h3><p><?php echo esc_html($locale==='ar'?'عرض الخيارات الحقيقية المتاحة لكل أداة.':'See the real options available for each instrument.'); ?></p></article><article><h3><?php echo esc_html($locale==='ar'?'تواصل مباشر':'Direct support'); ?></h3><p><?php echo esc_html($locale==='ar'?'شارك متطلباتك لطلب عرض سعر.':'Share your requirements for quotation support.'); ?></p></article></div></div></section>
<section class="rosa-preview-family-strip" data-preview-proof-role><div class="rosa-preview-rail"><div class="rosa-preview-family-strip__items"><?php foreach(['Knives','Scissors','Punches','Chisels','Cutters'] as $family): ?><span><?php echo esc_html(rosa_preview_family_label($family, $locale)); ?></span><?php endforeach; ?></div><div class="rosa-preview-proof"><strong><?php echo esc_html($locale==='ar'?'وضوح الكتالوج':'Clear catalogue references'); ?></strong><strong><?php echo esc_html($locale==='ar'?'وضوح التكوين':'Exact configuration visibility'); ?></strong><strong><?php echo esc_html($locale==='ar'?'دعم عروض الأسعار':'Direct quotation support'); ?></strong></div></div></section>
<div data-preview-contact-cta><?php get_template_part('template-parts/client-preview/cta-banner',null,['locale'=>$locale]); ?></div><?php get_footer();
