<?php
/** Template Name: Rosa Client Preview About */
if (! defined('ABSPATH')) { exit; }
$locale = rosa_preview_locale();
$c = static fn(string $key, string $en, string $ar): string => rosa_preview_content('about', $key, $locale, $locale === 'ar' ? $ar : $en);
get_header();
?>
<section class="rosa-preview-page-hero" data-preview-page-hero><div class="rosa-preview-rail"><p class="rosa-preview-eyebrow"><?php echo esc_html($c('page_eyebrow', 'ROSA', 'ROSA')); ?></p><h1><?php echo esc_html($c('page_title', 'About us', 'من نحن')); ?></h1><p><?php echo esc_html($c('page_body', 'Learn about Rosa’s approach to medical-instrument discovery and procurement support.', 'تعرف على نهج روزا في دعم اكتشاف الأدوات الطبية والتوريد.')); ?></p></div></section>
<section class="rosa-preview-split" data-preview-who-we-are><div class="rosa-preview-rail rosa-preview-split__grid"><div class="rosa-preview-split__media"><?php $img=rosa_preview_media_id('about_procurement'); if($img>0) echo wp_get_attachment_image($img,'large'); ?></div><div><p class="rosa-preview-eyebrow"><?php echo esc_html($c('who_eyebrow', 'Who we are', 'من نحن')); ?></p><h2><?php echo esc_html($c('who_title', 'A focused medical-instrument supply partner.', 'شريك متخصص في توريد الأدوات الطبية.')); ?></h2><p><?php echo esc_html($c('who_body', 'Rosa helps buyers navigate instrument families and catalogue references, then contact the team for procurement support.', 'يساعد موقع روزا المشترين على التنقل بين فئات الأدوات ومراجع الكتالوج والتواصل للحصول على دعم التوريد.')); ?></p></div></div></section>
<section class="rosa-preview-stats" data-preview-stats><div class="rosa-preview-rail rosa-preview-stats__grid"><?php $stats=[[$c('stat_1_value','5','5'),$c('stat_1_label','Product families','فئات منتجات')],[$c('stat_2_value','5','5'),$c('stat_2_label','Catalogue PDFs','كتالوجات')],[$c('stat_3_value','2','2'),$c('stat_3_label','Preview languages','لغات للمعاينة')]]; foreach($stats as [$n,$label]): ?><div><strong><?php echo esc_html($n); ?></strong><span><?php echo esc_html($label); ?></span></div><?php endforeach; ?></div></section>
<section class="rosa-preview-about-cards" data-preview-about-cards><div class="rosa-preview-rail rosa-preview-about-cards__grid"><?php $cards=[[$c('card_1_title','Product Families','فئات المنتجات'),$c('card_1_body','Five focused catalogue families for instrument discovery.','خمس فئات كتالوج رئيسية لاكتشاف الأدوات.'),$c('card_1_cta','Browse products','تصفح المنتجات')],[$c('card_2_title','Catalogue Support','دعم الكتالوج'),$c('card_2_body','Use family catalogues and product references to identify requirements.','استخدم الكتالوجات والمراجع لتحديد المتطلبات.'),$c('card_2_cta','View shop','عرض المنتجات')],[$c('card_3_title','Quotation Support','دعم عروض الأسعار'),$c('card_3_body','Contact Rosa with the required instrument/reference for procurement assistance.','تواصل مع روزا بالمراجع المطلوبة للحصول على مساعدة التوريد.'),$c('card_3_cta','Contact us','اتصل بنا')]]; foreach($cards as [$title,$body,$cta]): ?><article><h2><?php echo esc_html($title); ?></h2><p><?php echo esc_html($body); ?></p><a class="rosa-preview-text-link" href="<?php echo esc_url(home_url($locale==='ar'?'/ar/shop/':'/shop/')); ?>"><?php echo esc_html($cta); ?></a></article><?php endforeach; ?></div></section>
<section class="rosa-preview-feature" data-preview-feature-banner><div class="rosa-preview-rail rosa-preview-feature__grid"><div><?php $img=rosa_preview_media_id('about_hospitals'); if($img>0) echo wp_get_attachment_image($img,'large'); ?></div><div><p class="rosa-preview-eyebrow"><?php echo esc_html($c('feature_eyebrow','ROSA','ROSA')); ?></p><h2><?php echo esc_html($c('feature_title','Clear support for procurement requirements','دعم واضح لاحتياجات التوريد')); ?></h2><p><?php echo esc_html($c('feature_body','Start with a family or product reference, then contact us with what you need.','ابدأ بالفئة أو مرجع المنتج ثم تواصل معنا بالمطلوب.')); ?></p></div></div></section>
<section class="rosa-preview-why" data-preview-why-us><div class="rosa-preview-rail"><h2><?php echo esc_html($c('why_title','Support built around instrument procurement','دعم يركز على احتياجات توريد الأدوات')); ?></h2><div class="rosa-preview-why__grid"><article><h3><?php echo esc_html($c('why_1_title','Organized families','فئات منظمة')); ?></h3><p><?php echo esc_html($c('why_1_body','Browse instruments across five primary families.','تصفح الأدوات ضمن خمس فئات رئيسية.')); ?></p></article><article><h3><?php echo esc_html($c('why_2_title','Shareable references','مراجع قابلة للمشاركة')); ?></h3><p><?php echo esc_html($c('why_2_body','Use product names and references when contacting Rosa.','استخدم أسماء المنتجات والمراجع عند التواصل.')); ?></p></article><article><h3><?php echo esc_html($c('why_3_title','Direct contact','قناة تواصل مباشرة')); ?></h3><p><?php echo esc_html($c('why_3_body','Use email or phone for procurement support.','تواصل بالبريد أو الهاتف للحصول على مساعدة التوريد.')); ?></p></article></div></div></section>
<section class="rosa-preview-family-strip" data-preview-family-strip data-preview-proof-role><div class="rosa-preview-rail"><div class="rosa-preview-family-strip__items"><?php foreach(['Knives','Scissors','Punches','Chisels','Cutters'] as $family): ?><span><?php echo esc_html(rosa_preview_family_label($family, $locale)); ?></span><?php endforeach; ?></div><div class="rosa-preview-proof"><strong><?php echo esc_html($c('proof_1','Clear catalogue references','مراجع كتالوج واضحة')); ?></strong><strong><?php echo esc_html($c('proof_2','Contextual product imagery','صور سياقية')); ?></strong><strong><?php echo esc_html($c('proof_3','Direct contact support','دعم تواصل مباشر')); ?></strong></div></div></section>
<div data-preview-contact-cta><?php get_template_part('template-parts/client-preview/cta-banner',null,['locale'=>$locale,'image_id'=>rosa_preview_media_id('about_international')]); ?></div>
<?php get_footer();
