<?php
/** Template Name: Rosa Client Preview About */
if (! defined('ABSPATH')) { exit; }
$locale = rosa_preview_locale();
get_header();
?>
<section class="rosa-preview-page-hero" data-preview-page-hero><div class="rosa-preview-rail"><p class="rosa-preview-eyebrow">ROSA</p><h1><?php echo esc_html($locale==='ar'?'من نحن':'About us'); ?></h1><p><?php echo esc_html($locale==='ar'?'تعرف على نهج روزا في دعم اكتشاف الأدوات الطبية والتوريد.':'Learn about Rosa’s approach to medical-instrument discovery and procurement support.'); ?></p></div></section>
<section class="rosa-preview-split" data-preview-who-we-are><div class="rosa-preview-rail rosa-preview-split__grid"><div class="rosa-preview-split__media"><?php $img=rosa_preview_media_id('about_procurement'); if($img>0) echo wp_get_attachment_image($img,'large'); ?></div><div><p class="rosa-preview-eyebrow"><?php echo esc_html(rosa_preview_copy('who_eyebrow',$locale)); ?></p><h2><?php echo esc_html(rosa_preview_copy('who_title',$locale)); ?></h2><p><?php echo esc_html($locale==='ar'?'يساعد موقع روزا المشترين على التنقل بين فئات الأدوات ومراجع الكتالوج والتواصل للحصول على دعم التوريد.':'Rosa helps buyers navigate instrument families and catalogue references, then contact the team for procurement support.'); ?></p></div></div></section>
<section class="rosa-preview-stats" data-preview-stats><div class="rosa-preview-rail rosa-preview-stats__grid"><?php $stats=$locale==='ar'?[['5','فئات منتجات'],['5','كتالوجات'],['2','لغات للمعاينة']]:[['5','Product families'],['5','Catalogue PDFs'],['2','Preview languages']]; foreach($stats as [$n,$label]): ?><div><strong><?php echo esc_html($n); ?></strong><span><?php echo esc_html($label); ?></span></div><?php endforeach; ?></div></section>
<section class="rosa-preview-about-cards" data-preview-about-cards><div class="rosa-preview-rail rosa-preview-about-cards__grid"><?php $cards=$locale==='ar'?[['فئات المنتجات','خمس فئات كتالوج رئيسية لاكتشاف الأدوات.','تصفح المنتجات'],['دعم الكتالوج','استخدم الكتالوجات والمراجع لتحديد المتطلبات.','عرض المنتجات'],['دعم عروض الأسعار','تواصل مع روزا بالمراجع المطلوبة للحصول على مساعدة التوريد.','اتصل بنا']]:[['Product Families','Five focused catalogue families for instrument discovery.','Browse products'],['Catalogue Support','Use family catalogues and product references to identify requirements.','View shop'],['Quotation Support','Contact Rosa with the required instrument/reference for procurement assistance.','Contact us']]; foreach($cards as [$title,$body,$cta]): ?><article><h2><?php echo esc_html($title); ?></h2><p><?php echo esc_html($body); ?></p><a class="rosa-preview-text-link" href="<?php echo esc_url(home_url($locale==='ar'?'/ar/shop/':'/shop/')); ?>"><?php echo esc_html($cta); ?></a></article><?php endforeach; ?></div></section>
<section class="rosa-preview-feature" data-preview-feature-banner><div class="rosa-preview-rail rosa-preview-feature__grid"><div><?php $img=rosa_preview_media_id('about_hospitals'); if($img>0) echo wp_get_attachment_image($img,'large'); ?></div><div><p class="rosa-preview-eyebrow">ROSA</p><h2><?php echo esc_html($locale==='ar'?'دعم واضح لاحتياجات التوريد':'Clear support for procurement requirements'); ?></h2><p><?php echo esc_html($locale==='ar'?'ابدأ بالفئة أو مرجع المنتج ثم تواصل معنا بالمطلوب.':'Start with a family or product reference, then contact us with what you need.'); ?></p></div></div></section>
<section class="rosa-preview-why" data-preview-why-us><div class="rosa-preview-rail"><h2><?php echo esc_html(rosa_preview_copy('why_title',$locale)); ?></h2><div class="rosa-preview-why__grid"><article><h3><?php echo esc_html($locale==='ar'?'فئات منظمة':'Organized families'); ?></h3><p><?php echo esc_html($locale==='ar'?'تصفح الأدوات ضمن خمس فئات رئيسية.':'Browse instruments across five primary families.'); ?></p></article><article><h3><?php echo esc_html($locale==='ar'?'مراجع قابلة للمشاركة':'Shareable references'); ?></h3><p><?php echo esc_html($locale==='ar'?'استخدم أسماء المنتجات والمراجع عند التواصل.':'Use product names and references when contacting Rosa.'); ?></p></article><article><h3><?php echo esc_html($locale==='ar'?'قناة تواصل مباشرة':'Direct contact'); ?></h3><p><?php echo esc_html($locale==='ar'?'تواصل بالبريد أو الهاتف للحصول على مساعدة التوريد.':'Use email or phone for procurement support.'); ?></p></article></div></div></section>
<section class="rosa-preview-family-strip" data-preview-family-strip data-preview-proof-role><div class="rosa-preview-rail"><div class="rosa-preview-family-strip__items"><?php foreach(['Knives','Scissors','Punches','Chisels','Cutters'] as $family): ?><span><?php echo esc_html($family); ?></span><?php endforeach; ?></div><div class="rosa-preview-proof"><strong><?php echo esc_html($locale==='ar'?'مراجع كتالوج واضحة':'Clear catalogue references'); ?></strong><strong><?php echo esc_html($locale==='ar'?'صور سياقية':'Contextual product imagery'); ?></strong><strong><?php echo esc_html($locale==='ar'?'دعم تواصل مباشر':'Direct contact support'); ?></strong></div></div></section>
<div data-preview-contact-cta><?php get_template_part('template-parts/client-preview/cta-banner',null,['locale'=>$locale,'image_id'=>rosa_preview_media_id('about_international')]); ?></div>
<?php get_footer();
