<?php
/** Template Name: Rosa Client Preview Contact */
if (! defined('ABSPATH')) { exit; }
$locale = rosa_preview_locale();
$address = rosa_theme_business_value('address');
$phone = rosa_theme_business_value('phone');
$email = rosa_theme_business_value('email');
get_header();
?>
<section class="rosa-preview-page-hero" data-preview-page-hero><div class="rosa-preview-rail"><p class="rosa-preview-eyebrow">ROSA</p><h1><?php echo esc_html($locale==='ar'?'اتصل بنا':'Contact us'); ?></h1><p><?php echo esc_html(rosa_preview_copy('contact_title',$locale)); ?></p></div></section>
<section class="rosa-preview-contact" data-preview-contact-layout id="inquiry"><div class="rosa-preview-rail rosa-preview-contact__grid"><div class="rosa-preview-contact__details"><?php if($address!==''): ?><article data-preview-contact-location><span><?php echo esc_html($locale==='ar'?'الموقع':'Location'); ?></span><strong><?php echo esc_html($address); ?></strong></article><?php endif; ?><?php if($phone!==''): ?><article data-preview-contact-phone><span><?php echo esc_html($locale==='ar'?'اتصل بنا':'Call us'); ?></span><a href="tel:<?php echo esc_attr((string)preg_replace('/[^0-9+]/','',$phone)); ?>"><?php echo esc_html($phone); ?></a></article><?php endif; ?><?php if($email!==''): ?><article data-preview-contact-email><span><?php echo esc_html($locale==='ar'?'البريد الإلكتروني':'Email us'); ?></span><a href="mailto:<?php echo esc_attr($email); ?>"><?php echo esc_html($email); ?></a></article><?php endif; ?></div><div class="rosa-preview-contact__form-wrap"><h2><?php echo esc_html($locale==='ar'?'شارك متطلباتك':'Share your requirements'); ?></h2><form class="rosa-preview-contact-form" data-preview-contact-form><label><?php echo esc_html($locale==='ar'?'الاسم':'Name'); ?><input type="text" name="name" autocomplete="name"></label><label><?php echo esc_html($locale==='ar'?'الهاتف':'Phone'); ?><input type="tel" name="phone" autocomplete="tel"></label><label><?php echo esc_html($locale==='ar'?'الموضوع':'Subject'); ?><input type="text" name="subject"></label><label><?php echo esc_html($locale==='ar'?'الرسالة':'Message'); ?><textarea name="message" rows="5"></textarea></label><?php if($email!==''): ?><a class="rosa-preview-button rosa-preview-button--accent" href="mailto:<?php echo esc_attr($email); ?>"><?php echo esc_html($locale==='ar'?'إرسال عبر البريد الإلكتروني':'Send by email'); ?></a><?php endif; ?></form></div></div></section>
<section class="rosa-preview-map" data-preview-map-role><div class="rosa-preview-rail"><div class="rosa-preview-map__panel"><p class="rosa-preview-eyebrow"><?php echo esc_html($locale==='ar'?'الموقع':'Location'); ?></p><h2><?php echo esc_html($address); ?></h2><?php if($address!==''): ?><a class="rosa-preview-button" href="<?php echo esc_url('https://www.google.com/maps/search/?api=1&query='.rawurlencode($address)); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html($locale==='ar'?'البحث في الخرائط':'Search on maps'); ?></a><?php endif; ?></div></div></section>
<div data-preview-contact-cta><?php get_template_part('template-parts/client-preview/cta-banner',null,['locale'=>$locale]); ?></div>
<?php get_footer();
